config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "profiles/:id", to: "users#show", as: "profile"
  # Defines the root path route ("/")
  # root "posts#index"


  resources :meals, except: [:destroy] do
    resources :user_meals, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :meal_ingredients, only: [:create, :index]
  resources :user_diets, only: [:create, :index, :destroy]
  
  resources :diets, only: [:create, :index]
  resources :user_meals, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diet.rb
class Diet < ApplicationRecord
  has_many :meals, through: :meal_diets
  has_many :users, through: :user_diets
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :meals, through: :meal_ingredients
  validates :name, :unit, presence: true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :meal_ingredients
  has_many :ingredients, through: :meal_ingredients
  has_many :reviews
  accepts_nested_attributes_for :meal_ingredients
  has_many :meal_diets
  has_many :diets, through: :meal_diets
  has_one_attached :photo

  validates :cuisine, :description, :recipe, presence: true
end

app/models/meal_diet.rb
class MealDiet < ApplicationRecord
  belongs_to :diet
  belongs_to :meal
end

app/models/meal_ingredient.rb
class MealIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :meal
  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  validates :content, :rating, presence: true
  validates :rating, numericality: { in: (1..5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture
  has_many :user_diets
  has_many :diets, through: :user_diets
  has_many :reviews
  has_many :user_meals

  validates :address, :age, :last_name, :first_name, presence: true
end

app/models/user_diet.rb
class UserDiet < ApplicationRecord
  belongs_to :user
  belongs_to :diet
end

app/models/user_meal.rb
class UserMeal < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  validates :date, :time_of_day, presence: true
  TIMES = ["Breakfast", "Lunch", "Dinner", "Snack"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :address, :profile_picture])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age, :address])
  end
end

app/controllers/meal_ingredients_controller.rb
class MealIngredientsController < ApplicationController

  def index
    meal_ingredients_list = []
    @day_filter = params[:filter] ? params[:filter].to_i : 7
    current_user.user_meals.where(date: Date.today..Date.today + @day_filter).each do |user_meal|
      meal_ingredients_list << user_meal.meal.meal_ingredients
    end
    meal_ingredients_list.flatten!
    @grocery_list = Hash.new(0)

    meal_ingredients_list.each do |meal_ingredient|
      @grocery_list[meal_ingredient.ingredient_id] += meal_ingredient.quantity
    end

    @grocery_list = @grocery_list.sort_by do |ingredient_id, _quantity|
      Ingredient.find(ingredient_id).name
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index, :carousel]

  before_action :set_meals, only: [:show]

  def show
    @ingredients = @meal.meal_ingredients.includes(:ingredient)
    @user_meal = UserMeal.new
    @review = Review.new
  end

  def index
    @meals = Meal.all
    carousel
    if params[:query].present?
      sql_subquery = <<~SQL
        meals.name @@ :query
        OR meals.description @@ :query
        OR meals.cuisine @@ :query
        OR ingredients.name @@ :query
        OR diets.name @@ :query
      SQL
      @meals = @meals.joins(:ingredients)
                     .left_outer_joins(:diets)
                     .where(sql_subquery, query: "%#{params[:query]}%")
                     .distinct
    end
  end

  def new
    @meal = Meal.new
    @meal_ingredient = 10.times { @meal.meal_ingredients.build }
  end

  def create
    @meal_params = meal_params
    @meal_params[:meal_ingredients_attributes] = meal_params[:meal_ingredients_attributes].select { |id, hash| hash[:ingredient_id].present? }
    @meal = Meal.new(@meal_params)
    @meal.user = current_user

    if @meal.save
      redirect_to meal_path(@meal)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def carousel
    @japanese_list = Meal.where(cuisine: "Japanese")
    @indian_list = Meal.where(cuisine: "Indian")
    @italian_list = Meal.where(cuisine: "Italian")
    @thai_list = Meal.where(cuisine: "Thai")
    @cuisines = [@japanese_list, @indian_list, @italian_list, @thai_list]
  end

  private

  def set_meals
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :cuisine, :description, :recipe, :user, :ingredients, :photo, meal_ingredients_attributes: [:ingredient_id, :quantity]) #then add picture
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_meal, only: [:create]

  def create
    # create speichert das neue review in der Datenbank
    @review = Review.new(review_params)
    @review.meal = @meal
    @review.user = current_user
    if @review.save
      redirect_to meal_path(@meal)
    else
      # das Formular wird neu angezeigt wenn das speichern
      # nicht erfolgreich war
      render :new
    end
  end

  private

  def set_meal
    # sonst müsste ich in jeder Methode anstatt von
    # @booking = Booking.find(params[:booking_id]
    @meal = Meal.find(params[:meal_id])
  end

  def review_params
    # strong params
    params.require(:review).permit(:content, :rating, :meal, :user)
  end
end

app/controllers/user_diets_controller.rb
class UserDietsController < ApplicationController
  def create
    @user_diet = UserDiet.new(user_diet_params)
    @user_diet.user = current_user
    @user_diet.save
    redirect_to profile_path(current_user)
  end

  def destroy
    @user_diet = UserDiet.find(params[:id])
    @user_diet.destroy
    flash[:notice] = "Diet successfully removed."
    redirect_to profile_path(current_user)
  end

  private

  def user_diet_params
    params.require(:user_diet).permit(:diet_id)
  end
end

app/controllers/user_meals_controller.rb
class UserMealsController < ApplicationController


  def index
    @meals = UserMeal.where(user: current_user)
  end

  def create
    @user_meal = UserMeal.new(user_meal_params)
    @user_meal.user = current_user
    @user_meal.meal = Meal.find(params[:meal_id])
    if @user_meal.save
      redirect_to user_meals_path # then will redirect to calendar but for now this is fine
    end
  end


  private

  def user_meal_params
    params.require(:user_meal).permit(:date, :time_of_day, :meal_id, :user) # then add picture
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @diets = @user.diets
    @user_diets = Diet.all
    @user_diet = UserDiet.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumenu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/js/tom-select.complete.min.js"></script>
  </head>

  <body class="<%='bg' if params["controller"] == "devise/sessions" && params["action"] == "new"%> ">

    <% unless (params["controller"] == "devise/sessions" && params["action"] == "new") || (params["controller"] == "pages" && params["action"] == "home") || (params["controller"] == "devise/registrations" && params["action"] == "new")%>
    
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/meal_ingredients/index.html.erb
<h1 class="header_grocery_list">Grocery List</h1>
  <div class="dropdown-container" id="container_groceries">
    <div class="header_groceries">For the next:</div>
    <div class="dropdown">
      <button class="btn  dropdown" type="button" id="filter_button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= "#{@day_filter} days" %>
      </button>

      <ul class="dropdown-menu" id="day_filter_dropdown" aria-labelledby="dropdownMenuButton">

        <li><%= link_to "7 days", meal_ingredients_path(filter: 7) %></li>
        <li><%= link_to "14 days", meal_ingredients_path(filter: 14) %></li>
        <li><%= link_to "30 days", meal_ingredients_path(filter: 30) %></li>


      </ul>
    </div>
  </div>


<div class="grocery_list">
  <% @grocery_list.each do |ingredient_id, quantity| %>

    <li class="card" id="grocery_list">
      <div class="container" id="grocery-container">

        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
          <div class="ingredient_name"><%= Ingredient.find(ingredient_id).name %></div>
        </div>


        <div class="", id="quantity"><%= quantity %>
          <%= Ingredient.find(ingredient_id).unit %>
        </div>
      </div></li>
      <% end %>
</div>

app/views/meals/_card.html.erb
<div class="meal-card gx-0c" style = "background-image: url(<%= cl_image_path meal.photo.key%>)">
  <div class="meal-card-title-container">
    <%= link_to meal.name.upcase, meal_path(meal) %>
    <i class="bi bi-info-circle"></i>
  </div>
</div>

app/views/meals/_carocard.html.erb
<div class="carrousel-meal-card gx-0c" style = "background-image: url(<%= cl_image_path meal.photo.key%>)" %></span>
  <div class="meal-card-title-container carrousel-meal-card-title-container">
    <%= link_to meal.name.upcase, meal_path(meal) %>
    <div class="d-flex a-rating">
      <% rating = 0 %>
      <% meal.reviews.each do |review|%>
        <% rating += review.rating %>
      <% end %>
      <% unless rating == 0 %>
        <% rating = (rating/meal.reviews.size.to_f).round(1) %>
        <p><%= rating %></p>
        <i class="bi bi-star-fill"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/meals/_carousel.html.erb
<h2 id="mod-title"><i><%= "#{list.first.cuisine}".capitalize %></i></h2>
<div style = "padding: 5%;" id="carousel_<%=index%>" class="carousel slide" data-bs-ride="carousel">
    <div style = "padding: 5%;" class="carousel-inner">
      <% list.in_groups_of(1, false).each_with_index do |group, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
            <% group.each do |meal| %>
              <%= render "carocard", meal: meal %>
            <% end %>
        </div>
      <% end %>
    </div>


  <a class="carousel-control-prev" href="#carousel_<%=index%>" role="button" data-bs-slide="prev">
    <span style = "background-image: url(<%= asset_path("flecha_i.png") %>)" class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel_<%=index%>" role="button" data-bs-slide="next">
    <span style = "background-image: url(<%= asset_path("flecha_d.png") %>)"; class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>

app/views/meals/index.html.erb
<%# THIS PUTS ALL THE TYPES OF ANIMALS IN THEIR OWN ARRAY %>
<%# CALLING THE CAROUSEL %>

  <div class="all"  data-controller="toggle">

    <div class="d-flex searchbar">

      <%= form_with url: meals_path, method: :get, class: "mod-form d-flex" do %>

        <div class="position-relative">
          <i class="bi bi-sliders2" id="options" data-action="click->toggle#fire"></i>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Type a keyword"%>

          <%= button_tag nil, class: "btn mod-btn" do %>
              <i class="bi bi-search"></i>
          <% end %>
        </div>

      <% end %>
    </div>









      <div class="mod-body">
        <div class="filters d-none" data-toggle-target="togglableElement">
          <div class="d-flex"><i class="fa-solid fa-carrot"></i><%= link_to "Vegan", meals_path(query:"Vegan") %> </div>
          <div class="d-flex"><i class="fa-solid fa-pepper-hot"></i><%= link_to "Mexican", meals_path(query:"Mexican") %></div>
          <div class="d-flex"><i class="fa-solid fa-bowl-rice"></i><%= link_to "Japanese", meals_path(query:"Japanese") %></div>
          <div class="d-flex"><i class="fa-solid fa-bowl-food"></i><%= link_to "Indian", meals_path(query:"Indian") %></div>
          <div class="d-flex"><i class="fa-solid fa-fish-fins"></i><%= link_to "Fish", meals_path(query:"Fish") %></div>
          <div class="d-flex"><i class="fa-solid fa-cow"></i><%= link_to "Dairy Free", meals_path(query:"Dairy Free") %></div>
          <div class="d-flex"><i class="fa-solid fa-ice-cream"></i><%= link_to "Dessert", meals_path(query:"Dessert") %></div>
          <div class="d-flex"><i class="fa-solid fa-seedling"></i><%= link_to "Vegetarian", meals_path(query:"Vegetarian") %></div>
          <div class="d-flex"><i class="fa-solid fa-bacon"></i><%= link_to "American", meals_path(query:"American") %></div>
          <div class="d-flex"><i class="fa-solid fa-bread-slice"></i><%= link_to "Gluten free", meals_path(query:"Gluten Free") %></div>
          <div class="d-flex"><i class="fa-solid fa-pizza-slice"></i><%= link_to "Pizza", meals_path(query:"Pizza") %></div>
          <div class="d-flex"><i class="fa-solid fa-wine-glass"></i><%= link_to "French", meals_path(query:"French") %></div>
        </div>
        <% if params[:query].present? %>
          <h2 id="searched">Recipes for "<%= params[:query] %>"</h2>
          <div class="cards">
          <% @meals.each do |meal| %>
            <%= render "carocard", meal: meal %>
          <% end %>
          </div>
        <% else %>
          <%@cuisines.each_with_index do |meal_array, index| %>
          <br>
            <%unless meal_array.size == 0%>
              <%=render "carousel", list: meal_array, index: index %>
            <% end %>
          <br>
          <% end %>
        <% end %>
      </div>
  </div>

app/views/meals/new.html.erb
<div data-controller ="ingredient-qty" class="form-entire">

    <h1 style = "padding-left: 33px;">Post your Recipe</h5>

    <%= simple_form_for(@meal) do |f| %>
      <%= f.input :name,
                  placeholder: "Dish",
                  label: false%>
      <%= f.input :cuisine,
                  placeholder: "Cuisine",
                  label: false%>
      <%= f.input :photo, as: :file,
                  label: "Add a photo" %>
      <%= f.input :description,
                  placeholder: "Description",
                  label: false%>

      <%= f.fields_for :meal_ingredients, data: {ingredient_qty_target: "form"} do |ff|%>
        <div class = "post-form-qnty d-none"  data-ingredient-qty-target ="ingredientInput" >
          <%= ff.association :ingredient, collection: Ingredient.order(:name), :as => :select, input_html: { data: {controller: "tom-select"}}, class: "ingredient-quantity",
                              placeholder: "Ingredient"
                              %>
          <%= ff.input :quantity, class: "quantity-ingredient"%>
        </div>
      <% end %>

      <div style= "padding-left: 10px;">
        <i style = "padding-top: 0px; margin-top: 0px;"
        class="fa-solid fa-plus"
        data-action="click->ingredient-qty#ingredient"></i>
      </div>

      <%= f.input :recipe,
                  :label => false,
                  placeholder: "Instructions"%>

        <!-- add photo thing when we add cloudinary -->
      <%= f.submit "Post your recipe", class: "btn w-100 post_button"%>
    <% end %>
</div>

app/views/meals/show.html.erb
<div class = "meal_background_image" style="background-image: linear-gradient(rgba(0, 0, 0, 0.0),rgba(0, 0, 0, 0.2)), url(<%= cl_image_path @meal.photo.key%>)">
  <div data-controller="toggle" class = "calendar_button">
    <button data-action="click->toggle#fire" class="remolacha">+ Add to calendar</button>
    <div id="cal_form">
      <div data-toggle-target="togglableElement" class="d-none ">
        <%= simple_form_for([@meal, @user_meal]) do |f| %>
          <%= f.input :date%>
          <%= f.input :time_of_day, collection: UserMeal::TIMES, as: :select, id:"time_of_day" %>
          <%= f.submit "Add to calendar", class: "btn btn-primary w-100", id: "btn_post" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class = "meal_intro">
  <h1><%= @meal.name %></h1>
  <p><%= @meal.description %><p>
</div>

<div class = "description">
  <div class = "ingredients">
    <h2>Ingredients:</h2>
    <ul>
      <%@meal.meal_ingredients.includes(:ingredient).each do |meal_ingredient| %>
        <li> <%= meal_ingredient.quantity %> <%= meal_ingredient.ingredient.unit %> <%= meal_ingredient.ingredient.name %></li>
      <% end %>
    </ul>
  </div>

  <div class = "recipe">
    <h2>Instructions:</h2>
    <p><%= @meal.recipe %></p>
  </div>
</div>
<br>
<h3 style = "padding-left: 15px; ">Reviews</h3>
<div class= "review_form" >
  <%= simple_form_for([@meal, @review]) do |f| %>
    <div class="d-flex review-form-content">
      <%= f.input :content, placeholder: "Write a review...", label: false %>
      <%= f.input :rating, collection: (1..5).to_a, as: :select, placeholder: "Rate it...", label: "Rating" %>
    </div>
    <div class="d-flex align-items-center">
      <%= f.submit "Submit", class: "btn submit_review"%>
    </div>
  <% end %>

  <% @meal.reviews.each do |review| %>
    <div class= "review-card">
        <div class="notification">

        <div class="notification-content">
          <% if review.user.profile_picture.attached? %>
              <%= cl_image_tag review.user.profile_picture.key, alt:"Profile Image", class:"avatar-large"%>
          <%end%>
          <p><%= review.user.first_name %> <%= review.user.last_name %></p>
        </div>
        <div class = "stars">
          <% review.rating.times do  %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="fa-regular fa-star" style="padding-bottom: 10px;"></i>
          <% end %>
        </div>
        <p><%=review.content %></p>
        <% if review.user == current_user%>
          <div class="notification-actions">
            <a href="#">Edit <i class="fas fa-pencil-alt"></i></a>
            <a href="#">Delete <i class="far fa-trash-alt"></i></a>
          </div>
        <%end%>

      </div>
    </div>
<% end %>
</div>

app/views/pages/home.html.erb
<div class="banner">
    <%= image_tag "https://res.cloudinary.com/do9ythsfg/image/upload/v1725449081/NewLandingPageNew_wzwhiy.png", class: "banner-img" %>
    <div class="banner-content">
        <h1 class="welcome-logo">TÚMENU</h1>
        <h2 id="slogan">Recipes made easy<br/>plan your week with pleasure!</h2>
        <%= link_to "Get started", meals_path, class: "btn btn-primary", type: "button", id: "lets_get_started_button" %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-tumenu">
  <div class="container-fluid" id="container_nav">
    <%= link_to meals_path do %>
      <h1 id="logo">TÚMENU</h1>
    <% end %>
    <% unless current_user %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success", type: "button", id: "sign_up_button" %>
    <% else %>
      <div id="asparagus" data-controller="toggle">
      <i class="bi bi-list" data-action="click->toggle#fire2"></i>
        <div id="profile_options" class="d-none" data-toggle-target="togglableElemento">
          <%= link_to "Post a Recipe", new_meal_path %>
          <%= link_to "My Calendar", user_meals_path %>
          <%= link_to "Grocery", meal_ingredients_path %>
          <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete} %>
        </div>
        <% if current_user.profile_picture.attached? %>
          <%= link_to profile_path(current_user) do %>
            <%= cl_image_tag current_user.profile_picture.key, alt:"user Image", class:"avatar", style:"object-fit: cover"%>
          <% end %>
        <% else %>
          <%= link_to profile_path(current_user) do %>
            <%= image_tag "https://res.cloudinary.com/do9ythsfg/image/upload/v1725461237/default-avatar-icon-of-social-media-user-vector_xldyl1.jpg" , alt:"user Image", class:"avatar", style:"object-fit: cover"%>
          <% end %>
        <%end%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="card" id="profile_card">
    <div class= "container" id="container_profile">
      <div id="profile_picture">
          <% if @user.profile_picture.attached? %>
            <%= cl_image_tag @user.profile_picture.key, alt:"user Image", class:"scaled-image", style:"object-fit: cover"%>
          <% end %>
      </div>


      <div class="" id="full_name">
          <%= @user.first_name %>
          <%= @user.last_name %><br/>
      </div>

      <div class="" id="age">
        <p class="profile_age"><strong>Age:</strong> <%= @user.age %></p>
      </div>


   </div>

    <div class="d-flex align-items-center mb-4">
      <i class="fa-solid fa-house me-5"></i>
      <p class="mb-0"><%= @user.address %></p>
    </div>

    <div class="d-flex align-items-center">
      <i class="fa-regular fa-envelope me-5"></i>
      <p class="mb-0"><%= @user.email %></p>
    </div>


    <div class="mt-5" id="diets_details">

      <div class="d-flex align-items-center">
        <div class="profile_diets_headers">Dietary restrictions:</div>
        <% if (Diet.all - @user.diets).any? %>
          <div class="user_diets_form">
            <%= simple_form_for(@user_diet, html: { id: "user_diet_form" }) do |f| %>
              <%= f.input :diet_id, collection: Diet.all - @user.diets, prompt: "+", input_html: { onchange: "this.form.submit();", class:"input_field diets_input" }, wrapper: false, label: false %>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="profile_diets d-flex flex-wrap gap-3">
        <% @user.user_diets.each do |user_diet| %>
          <div class="d-flex">
            <div class="remove_button">
              <%= link_to "-", user_diet_path(user_diet), data: {turbo_method: :delete} %>
            </div>
            <span class="diet_item">
              <%= user_diet.diet.name %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
</div>